repos:
  # Next hooks are Code Quality hooks.
  # If you want them to run on each commit, uncomment them
  # These are OPTIONAL.
  - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.14.0
    hooks:
      - id: pretty-format-golang
        args:
          - --autofix
  - repo: https://github.com/melisource/fury_datasec-git-hooks
    rev: 1.0.3
    hooks:
      - id: pre_commit_hook
        stages: [ commit ]
        verbose: true